export const API_CONFIG = {
    baseUrl: process.env.EXPO_PUBLIC_API_URL,
    endpoints: {
        login: '/api/login',
        homeCasero: '/api/home/casero',
        register: '/api/register',
        postAd: '/api/postad',
        editAd: '/api/editad',
        homeInquilino: '/api/home/inquilino',
        registrarSolicitud: '/api/solicitudes/crear',
        cargarSolicitudes: '/api/solicitudes/casero',
        procesarSolicitud: '/api/solicitudes/procesar',
        valorarUsuario: '/api/valoraciones/usuario',
        enviarCalificacionesUsuario: '/api/valoraciones/usuario/enviar',
        registrarInteraccion: '/api/interaccion/new',
        eliminarFavoritos: '/api/interaccion/eliminarFavoritos',
        guardarRespuestasTest: '/api/valoraciones/test/guardar',
        getPerfilInquilino: '/api/perfil/inquilino',
        editProfile: '/api/edit/profile',
    },
    motorUrl: process.env.EXPO_PUBLIC_MOTOR_URL,
};